### ISSUE TITLE
Theme apparently requires launching through X11

### ISSUE THREAD

**Issue by ralsei** [cqql/xresources-theme#1]
not sure if this is a hard requirement for it to work at all, but when launching `emacs -nw`, I get this:
    Warning (initialization): An error occurred while loading `/home/arc/.emacs.d/i\
    nit.el':

```
error: Window system is not in use or not initialized

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

**Comment by martenlienen** [comment]
This theme uses `x-get-resource` to read the color values from the X-server defaults database. So I guess there is not really a way around it.

**Comment by ralsei** [comment]
aight
