### ISSUE TITLE
Some colors are off and some fields are not visible.

### ISSUE THREAD

**Issue by amtoine** [cqql/xresources-theme#11]
I really like this project as I was looking for a way to synchronize my *doom Emacs* theme with the rest of my desktop.

However, it appears that some of the colors are off -I might just be used to the doom themes though and that's not that important :wink:- and some fields are not visible using the `xresources` theme.

For instance:
- this is the [`doom-gruvbox`](https://github.com/doomemacs/themes/blob/master/themes/doom-gruvbox-theme.el) theme from *doom Emacs*: one can see `doom` being higlighted with a `/doom` search and the line under the cursor inside *dired* at the bottom.
 ![emacs-doom-gruv](https://user-images.githubusercontent.com/44101798/157912742-06b125c1-753d-406b-b3d5-69de1a1c4acb.png)
 - this is the `xresources` theme from my personal [`.Xresources`](https://github.com/a2n-s/dotfiles/blob/c708161a2657316e509e3f41bdeced7d99bd0e89/.Xresources) file: `doom` is not visible nor is the selected line in *dired*
![emacs-xres-gruv](https://user-images.githubusercontent.com/44101798/157912757-451ee347-1a01-4b98-b104-360d79b6268f.png)

these are the exact same windows during the exact same session
this is a bit annoying but I really like your project...

**any idea to make it more readable?**

**Comment by martenlienen** [comment]
You would probably have to define colors for extra faces for things like search matches. I am open to PRs on this project but unfortunately am unable to work on this myself.

**Comment by amtoine** [comment]
no worries!
i'll see what i can do when i find some time :yum:

**Comment by martenlienen** [comment]
Great, looking forward to it :)
