### ISSUE TITLE
xresources-theme fails to load

### ISSUE THREAD

**Issue by ghost** [cqql/xresources-theme#8]
Hello, I recently installed xresources-theme but it fails to load and gives me this error:

`Error (use-package): xresources-theme/:init: Invalid face underline: :style, wave, :color, nil`

Is there anything I can do?

**Comment by ghost** [comment]
I must also add that the theme was working fine before I do not know what changed. Emacs version is 26.1

**Comment by martenlienen** [comment]
From the error I would guess that one of the colors red, yellow or cyan are `nil`. Can you evaluate `(xresources-theme-color "color1")` in ielm? Or equivalently the built-in `(x-get-resource "color1" "")`. This should give you a color code like `"#cc241d"`. But from your error it looks like it results in `nil` which points to a problem with your xrdb/Xresources setup.
