### ISSUE TITLE
Feature request: Reload without restart?

### ISSUE THREAD

**Issue by GeekyPeas** [cqql/xresources-theme#9]
Will it be possible to somehow reload emacs without having to restart it. 

URxvt for example can be reloaded using a SIGHUP signal (reference: https://github.com/regnarg/urxvt-config-reload)

I was wondering if emacs could do the same?

**Comment by martenlienen** [comment]
It is not possible directly, no. Even the plugin in that you linked to starts a new process, gets it to dump its configuration and then applies the configuration values to the currently running instance. In that regard, the same thing could be implemented in emacs but that is out of scope of a theme package and would be better suited for an independent package.

**Comment by GeekyPeas** [comment]
You are correct - the above functionality doesn't belong to a theme package. But I have made some progress on how to implement it.

I now have the following in my `.emacs`:

```
(defun sigusr1-handler ()
  (interactive)
  (load-file "~/.emacs"))
(define-key special-event-map [sigusr1] 'sigusr1-handler)

```

where I have the code to load `xresource-theme.el` also in my `.emacs`, then I noticed that running `kill -USR1 <emacs-pid>` actually reloads the `xresources-theme` as expected.

The problem is with how `xresources-theme.el` works. The problem is that `xresources-theme` uses `x-get-resource` which doesn't return the updated values from the `.Xresource` file until `emacs` is closed and re-started.

So suppose we parsed the `.Xresources` file and extracted the colors from it and used it in the `xresources-theme.el` then the `SIGUSR1` trick will work!

I know it will work as I verified the following: I replaced `(background (xresources-theme-color "background"))` with `(background "#AA0000")` in `xresouces-theme.el` and then executed  `kill -USR1 <emacs-pid>` and viola my background became a horrible red color!

Unfortunately, I am no `lisp` expert and the task of parsing `.Xresources` to extract colors from it is too much for me. I am trying to do what I can. But I will appreciate, if others pitched in work on this idea.

p.s.: Of course, I can write a `bash` script (where I can use `sed`) and generate an `.el` file with all the relevant details and use `SIGUSR1` to load it. That would do the job. But it will be too ugly and any emacs user should be horrified. We should do this in `lisp`!

**Comment by GeekyPeas** [comment]
Alright I solved it by cheating - aka invoking `bash` within `elisp`. Here is my solution:

```
(defun xresources-theme-color (name)
  "Read the color NAME (e.g. color5) from the X resources."
  (shell-command-to-string (format "xrdb -q | grep \"%s\" | awk '{print $2}' | tr -d \"\\n\"" (concat "*\\(.*\\)" name ":")))
  )

```
If one uses this definition of `xresources-theme-color` then one can load the `xresource-theme.el` without having to restart `emacs`.

And in-fact one can use the `SIGUSR1` signal trick that I mentioned to update all `emacs` instance simultaneously by running `kill -USR1 $(pgrep emacs)`. 

I am aware the above solution is not robust. It uses `grep` which can be tricky - it can match to things not intended as people have different ways of writing their `.Xresources` file. 

Will be happy to hear any criticism or feedbacks on the above.

**Comment by GeekyPeas** [comment]
I took a stab at this related question on emacs-stackexchange: 

https://emacs.stackexchange.com/questions/33974/reloading-xresources-colors-on-the-fly/53021#53021

**Comment by martenlienen** [comment]
Great, that you got it to work! A few notes from me

- Your solution will add quite a bit of load time because of all the shelling
- Using `defadvice` for the modification will leave the source file alone and be thus more robust against package updates
- As you already said, this hack is less robust than the official Xresources API in emacs with regards to different ways to configure emacs via `.Xresources`
